version: "3.8"
services:

  ingress-db:
    image: mysql
    container_name: ingress-db
    restart: always
    volumes:
      - ingress-db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  ingress-phpmyadmin:
    image: phpmyadmin
    container_name: ingress-phpmyadmin
    restart: always
    depends_on:
      - ingress-db
    ports:
      - 8080:80
    environment:
      PMA_HOST: ingress-db
    networks:
      - dev

  ingress-api:
    build: php
    container_name: ingress-api
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  ingress-db-data:
